// Generated by gencpp from file ywu_lab3/aStar.msg
// DO NOT EDIT!


#ifndef YWU_LAB3_MESSAGE_ASTAR_H
#define YWU_LAB3_MESSAGE_ASTAR_H

#include <ros/service_traits.h>


#include <ywu_lab3/aStarRequest.h>
#include <ywu_lab3/aStarResponse.h>


namespace ywu_lab3
{

struct aStar
{

typedef aStarRequest Request;
typedef aStarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct aStar
} // namespace ywu_lab3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ywu_lab3::aStar > {
  static const char* value()
  {
    return "dcbb5abadadc742196f01dc62dfaa036";
  }

  static const char* value(const ::ywu_lab3::aStar&) { return value(); }
};

template<>
struct DataType< ::ywu_lab3::aStar > {
  static const char* value()
  {
    return "ywu_lab3/aStar";
  }

  static const char* value(const ::ywu_lab3::aStar&) { return value(); }
};


// service_traits::MD5Sum< ::ywu_lab3::aStarRequest> should match 
// service_traits::MD5Sum< ::ywu_lab3::aStar > 
template<>
struct MD5Sum< ::ywu_lab3::aStarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ywu_lab3::aStar >::value();
  }
  static const char* value(const ::ywu_lab3::aStarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ywu_lab3::aStarRequest> should match 
// service_traits::DataType< ::ywu_lab3::aStar > 
template<>
struct DataType< ::ywu_lab3::aStarRequest>
{
  static const char* value()
  {
    return DataType< ::ywu_lab3::aStar >::value();
  }
  static const char* value(const ::ywu_lab3::aStarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ywu_lab3::aStarResponse> should match 
// service_traits::MD5Sum< ::ywu_lab3::aStar > 
template<>
struct MD5Sum< ::ywu_lab3::aStarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ywu_lab3::aStar >::value();
  }
  static const char* value(const ::ywu_lab3::aStarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ywu_lab3::aStarResponse> should match 
// service_traits::DataType< ::ywu_lab3::aStar > 
template<>
struct DataType< ::ywu_lab3::aStarResponse>
{
  static const char* value()
  {
    return DataType< ::ywu_lab3::aStar >::value();
  }
  static const char* value(const ::ywu_lab3::aStarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YWU_LAB3_MESSAGE_ASTAR_H
