// Generated by gencpp from file ywu_lab3/aStarRequest.msg
// DO NOT EDIT!


#ifndef YWU_LAB3_MESSAGE_ASTARREQUEST_H
#define YWU_LAB3_MESSAGE_ASTARREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ywu_lab3
{
template <class ContainerAllocator>
struct aStarRequest_
{
  typedef aStarRequest_<ContainerAllocator> Type;

  aStarRequest_()
    : x0(0)
    , y0(0)
    , x1(0)
    , y1(0)  {
    }
  aStarRequest_(const ContainerAllocator& _alloc)
    : x0(0)
    , y0(0)
    , x1(0)
    , y1(0)  {
    }



   typedef int32_t _x0_type;
  _x0_type x0;

   typedef int32_t _y0_type;
  _y0_type y0;

   typedef int32_t _x1_type;
  _x1_type x1;

   typedef int32_t _y1_type;
  _y1_type y1;




  typedef boost::shared_ptr< ::ywu_lab3::aStarRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ywu_lab3::aStarRequest_<ContainerAllocator> const> ConstPtr;

}; // struct aStarRequest_

typedef ::ywu_lab3::aStarRequest_<std::allocator<void> > aStarRequest;

typedef boost::shared_ptr< ::ywu_lab3::aStarRequest > aStarRequestPtr;
typedef boost::shared_ptr< ::ywu_lab3::aStarRequest const> aStarRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ywu_lab3::aStarRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ywu_lab3::aStarRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ywu_lab3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ywu_lab3::aStarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ywu_lab3::aStarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ywu_lab3::aStarRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03e03483e99199fa7bd12bfbdb79e3e2";
  }

  static const char* value(const ::ywu_lab3::aStarRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03e03483e99199faULL;
  static const uint64_t static_value2 = 0x7bd12bfbdb79e3e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ywu_lab3/aStarRequest";
  }

  static const char* value(const ::ywu_lab3::aStarRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x0\n\
int32 y0\n\
int32 x1\n\
int32 y1\n\
\n\
";
  }

  static const char* value(const ::ywu_lab3::aStarRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x0);
      stream.next(m.y0);
      stream.next(m.x1);
      stream.next(m.y1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct aStarRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ywu_lab3::aStarRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ywu_lab3::aStarRequest_<ContainerAllocator>& v)
  {
    s << indent << "x0: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x0);
    s << indent << "y0: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y0);
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YWU_LAB3_MESSAGE_ASTARREQUEST_H
